using System.Collections.Generic;
using Verse;

namespace RimSynapse.StoryTeller.Models
{
    /// <summary>
    /// Extended faction tracker owned by StoryTeller.
    /// Contains goodwill history, custom natural goodwill overrides,
    /// and faction history text generated by the LLM.
    /// Stored in SynapseStoryTellerWorldComponent.
    /// </summary>
    public class FactionStoryTracker : IExposable
    {
        public string factionId;
        public List<GoodwillSample> goodwillHistory = new List<GoodwillSample>();
        public float goodwillIntegral;
        public int lastEventTick;

        /// <summary>Custom natural goodwill override set by world generation (random offset).</summary>
        public int? customNaturalGoodwill;
        /// <summary>Reason for the custom natural goodwill (e.g., "World generation offset").</summary>
        public string customNaturalGoodwillReason;
        /// <summary>LLM-generated historical record for this faction.</summary>
        public string factionHistory;
        /// <summary>Absolute tick when the faction history was generated.</summary>
        public long historyGeneratedTick;

        public void ExposeData()
        {
            Scribe_Values.Look(ref factionId, "factionId");
            Scribe_Collections.Look(ref goodwillHistory, "goodwillHistory", LookMode.Deep);
            Scribe_Values.Look(ref goodwillIntegral, "goodwillIntegral");
            Scribe_Values.Look(ref lastEventTick, "lastEventTick");

            if (Scribe.mode == LoadSaveMode.PostLoadInit)
            {
                if (goodwillHistory == null)
                    goodwillHistory = new List<GoodwillSample>();
            }

            Scribe_Values.Look(ref customNaturalGoodwill, "customNaturalGoodwill", null);
            Scribe_Values.Look(ref customNaturalGoodwillReason, "customNaturalGoodwillReason", null);
            Scribe_Values.Look(ref factionHistory, "factionHistory", null);
            Scribe_Values.Look(ref historyGeneratedTick, "historyGeneratedTick", 0L);
        }
    }
}
