using System;
using HarmonyLib;
using RimWorld;
using Verse;

namespace RimSynapse.StoryTeller
{
    /// <summary>
    /// Intercepts major threat letters to rewrite their text via LLM,
    /// adding Synapse's spunky personality and commenting on the difficulty.
    /// </summary>
    [HarmonyPatch(typeof(LetterStack), "ReceiveLetter", new Type[] { typeof(Letter), typeof(string), typeof(int), typeof(bool) })]
    public static class Patch_LetterStack_ReceiveLetter
    {
        private static System.Collections.Generic.HashSet<Letter> _processedLetters = new System.Collections.Generic.HashSet<Letter>();

        public static bool Prefix(LetterStack __instance, Letter let, string debugInfo, int delayTicks, bool playSound)
        {
            if (_processedLetters.Contains(let))
            {
                return true; // Let vanilla run this time
            }

            // Only intercept if Synapse is the active storyteller
            if (Find.Storyteller?.def?.defName != "Synapse")
            {
                return true;
            }

            // Only intercept big threats (like raids, infestations, etc.)
            if (let.def != LetterDefOf.ThreatBig)
            {
                return true;
            }

            // Only ChoiceLetter has easily modifiable label/text fields. Most letters are ChoiceLetters.
            if (!(let is ChoiceLetter choiceLetter))
            {
                return true;
            }

            string originalName = choiceLetter.Label;
            string originalDesc = choiceLetter.Text;
            string difficultyName = Find.Storyteller.difficultyDef?.label ?? "unknown difficulty";

            string systemPrompt = @"You are Synapse, the AI Storyteller in RimWorld.
A major threat has just been generated by the game engine. Your job is to rewrite the event notification letter to fit your personality.
You are spunky, slightly antagonistic, and aware of the player's suffering. If they are playing on a high difficulty setting, remind them that 'they asked for this'. Occasionally throw in a sarcastic 'good luck'.
Retain all factual gameplay elements (the type of threat, what faction is attacking, etc.).

You MUST respond strictly in valid JSON format:
{
  ""label"": ""The rewritten letter title"",
  ""text"": ""The rewritten letter description...""
}";

            string userMessage = $@"Vanilla Event Title: {originalName}
Vanilla Event Description: {originalDesc}
Current Game Difficulty: {difficultyName}

Rewrite this threat notification to include your personality.";

            SynapseClient.PromptAsync(
                RimSynapseStoryTellerMod.ModHandle,
                systemPrompt,
                userMessage,
                result => 
                {
                    if (result.success)
                    {
                        try
                        {
                            string json = result.content.Trim();
                            int startIndex = json.IndexOf("{");
                            int endIndex = json.LastIndexOf("}");
                            if (startIndex >= 0 && endIndex >= startIndex)
                            {
                                json = json.Substring(startIndex, endIndex - startIndex + 1);
                            }
                            else
                            {
                                throw new Exception("No valid JSON object found in response.");
                            }

                            var parsed = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.Dictionary<string, string>>(json);
                            if (parsed != null)
                            {
                                if (parsed.TryGetValue("label", out string newName))
                                {
                                    choiceLetter.Label = newName;
                                }
                                if (parsed.TryGetValue("text", out string newDesc))
                                {
                                    choiceLetter.Text = newDesc;
                                }
                            }
                        }
                        catch (Exception ex)
                        {
                            Log.Warning($"[RimSynapse-StoryTeller] Failed to parse letter rewrite JSON: {ex.Message}");
                            choiceLetter.Label = originalName;
                            choiceLetter.Text = originalDesc;
                        }
                    }

                    SynapseGameComponent.Enqueue(() =>
                    {
                        _processedLetters.Add(choiceLetter);
                        // Send the modified letter to the stack
                        Find.LetterStack.ReceiveLetter(choiceLetter, debugInfo, delayTicks, playSound);
                    });
                },
                new ChatOptions { priority = 10 }
            );

            return false; // Skip the vanilla letter send for now, it will be added when the LLM returns.
        }
    }
}
