using System;
using HarmonyLib;
using RimWorld;
using Verse;

namespace RimSynapse.StoryTeller
{
    /// <summary>
    /// Intercepts quest letter delivery to rewrite quest titles and descriptions via LLM,
    /// giving each quest a narrative flavor that fits your colony's current story.
    /// </summary>
    [HarmonyPatch(typeof(QuestUtility), "SendLetterQuestAvailable")]
    public static class Patch_QuestUtility_SendLetterQuestAvailable
    {
        private static System.Collections.Generic.HashSet<Quest> _processedQuests = new System.Collections.Generic.HashSet<Quest>();

        public static bool Prefix(Quest quest)
        {
            if (_processedQuests.Contains(quest))
            {
                return true; // Let vanilla run this time
            }

            // Don't intercept story quests or endgame quests
            if (quest.root.defName.Contains("Endgame") || quest.root.defName.Contains("Archonexus"))
            {
                return true;
            }

            string originalName = quest.name;
            string originalDesc = quest.description;

            string systemPrompt = @"You are Synapse, the AI Storyteller in RimWorld.
A new quest has been generated by the game engine. Your job is to rewrite the quest title and description to fit the current narrative of the colony, while retaining all factual gameplay elements (rewards, threats, duration).
Make the flavor text dramatic, compelling, and contextualized.

You MUST respond strictly in valid JSON format:
{
  ""name"": ""The rewritten title"",
  ""description"": ""The rewritten description...""
}";

            string userMessage = $@"Vanilla Quest Title: {originalName}
Vanilla Quest Description: {originalDesc}

Rewrite this quest to fit the narrative.";

            SynapseClient.PromptAsync(
                RimSynapseStoryTellerMod.ModHandle,
                systemPrompt,
                userMessage,
                result => 
                {
                    if (result.success)
                    {
                        try
                        {
                            string json = result.content.Trim();
                            int startIndex = json.IndexOf("{");
                            int endIndex = json.LastIndexOf("}");
                            if (startIndex >= 0 && endIndex >= startIndex)
                            {
                                json = json.Substring(startIndex, endIndex - startIndex + 1);
                            }
                            else
                            {
                                throw new Exception("No valid JSON object found in response.");
                            }

                            var parsed = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.Dictionary<string, string>>(json);
                            if (parsed != null)
                            {
                                if (parsed.TryGetValue("name", out string newName))
                                {
                                    quest.name = newName;
                                }
                                if (parsed.TryGetValue("description", out string newDesc))
                                {
                                    quest.description = newDesc;
                                }
                            }
                        }
                        catch (Exception ex)
                        {
                            RimSynapse.SynapseLog.Warn("storyteller", $"[RimSynapse-StoryTeller] Failed to parse quest rewrite JSON: {ex.Message}");
                            quest.name = originalName;
                            quest.description = originalDesc;
                        }
                    }

                    SynapseGameComponent.Enqueue(() =>
                    {
                        _processedQuests.Add(quest);
                        QuestUtility.SendLetterQuestAvailable(quest);
                    });
                },
                new ChatOptions { priority = 10 }
            );

            return false; // Skip the vanilla letter send for now
        }
    }
}

